################################################################################
# 変数(.gitignore)
################################################################################
IGNORE_LIST    := intellij+all,linux,macos,windows,vim,emacs
GIT_IGNORE_URL := https://www.toptal.com/developers/gitignore/api/$(IGNORE_LIST)
